export const ADD_TODO = 'ADD_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const SET_EDITTING_ID = 'SET_EDITTING_ID'
export const RESET_EDITTING_ID = 'RESET_EDITTING_ID'
export const CLEAR_ALL = 'CLEAR_ALL'
export const TOGGLE_TODO_STATUS = 'TOGGLE_TODO_STATUS'

export const ADD_MANY_MONSTER = 'ADD_MANY_MONSTER'
export const ADD_MONSTER = 'ADD_MONSTER'
export const DEATH = 'DEATH'

export const SUCCESS_GEN_RAND_NUM = 'SUCCESS_GEN_RAND_NUM'
export const FAIL_GEN_RAND_NUM = 'FAIL_GEN_RAND_NUM'

export const FETCH_BOARD_LIST = 'FETCH_BOARD_LIST'
export const FETCH_BOARD = 'FETCH_BOARD'

export const FETCH_PRODUCT_LIST = 'FETCH_PRODUCT_LIST'
export const FETCH_PRODUCT = 'FETCH_PRODUCT'

export const FETCH_MONSTER_LIST = 'FETCH_MONSTER_LIST'
export const FETCH_MONSTER = 'FETCH_MONSTER'

export const ALLOC_RANDOM_DUNGEON = 'ALLOC_RANDOM_DUNGEON'

export const SCORE_MANAGEMENT = 'SCORE_MANAGEMENT'

export const CRAWL_START = 'CRAWL_START'