server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/non_jpa_db?serverTimezone=UTC&useSSL=false
    username: khweb
    password: khWeb@123
    diver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG